// <auto-generated />
using System;
using ASP.NET_Assignment_04.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Assignment_04.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20211204051005_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "64",
                            Content = "What is the total number of squares on a chess board?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "modern",
                            Content = "Which of the following is not a format of a chess game",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "grand master",
                            Content = "What is the highest title for professional chess players?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "castles",
                            Content = "What is the other name for the rooks?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "game theory",
                            Content = "Strategies in chess are used by economists as a basis for which theory?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer = "russia",
                            Content = "Which country has the most grandmasters?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer = "magnus carlsen",
                            Content = "Who is the current world chess champion?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer = "risks one or more pawns or a minor piece to gain an advantage in position",
                            Content = "What is a gambit in chess?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer = "deep blue",
                            Content = "What is the name of the computer which defeated the former world champion Garry Kasparov?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer = "19th",
                            Content = "What century did the modern rules for chess standardised?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer = "pawns",
                            Content = "Which piece can only move in a forward direction?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer = "2500",
                            Content = "To be awarded the Grandmaster title, a player must have at least how many points in the ELO rating?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 13,
                            Answer = "5949 moves",
                            Content = "The longest chess game theoretically possible is?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 14,
                            Answer = "the king is dead",
                            Content = "The word checkmate is derived from the Arabic word shah mat, which means",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 15,
                            Answer = "1090",
                            Content = "The modern chess board as we see it today appeared first in Europe in the year",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 16,
                            Answer = "rookies",
                            Content = "Players in their first year are called",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 17,
                            Answer = "game of kings",
                            Content = "Chess is also called the?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 18,
                            Answer = "L shape",
                            Content = "Knights move in what shape?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 19,
                            Answer = "the queen",
                            Content = "What is the strongest piece in chess",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 20,
                            Answer = "the king",
                            Content = "What is the most important piece in chess",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 21,
                            Answer = "arsenal",
                            Content = "Soccer made its television debut in 1937, featuring what team in england",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 22,
                            Answer = "norway",
                            Content = "What team has never lost to Brzil in international competition",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 23,
                            Answer = "c. ronaldo",
                            Content = "the only known football player in professional history to score a goal in every single minute of a match?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 24,
                            Answer = "neymar",
                            Content = "The most expensive transfer in soccer history was by which players",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 25,
                            Answer = "number 10",
                            Content = "What number is unofficially considered the kit number for the best player on a squad",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 26,
                            Answer = "pele",
                            Content = "What player has won the most world cups",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 27,
                            Answer = "3",
                            Content = "Hat-trick is when a player scores how many goals?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 28,
                            Answer = "8",
                            Content = "How many countries have won the world cup",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 29,
                            Answer = "2 times",
                            Content = "How many times has france won the world cup",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 30,
                            Answer = "england",
                            Content = "What country created the first professional league",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 31,
                            Answer = "messi",
                            Content = "Which player has the most ballon d'or",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 32,
                            Answer = "escobar",
                            Content = "What player scored an own goal for Columbia in the 1994 World Cup?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 33,
                            Answer = "the referee",
                            Content = "The person who controls the match and enforces the laws of the game is?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 34,
                            Answer = "11",
                            Content = "There are how many players on a soccer team",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 35,
                            Answer = "pitch",
                            Content = "A soccer field is also called a?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 36,
                            Answer = "pakistan",
                            Content = "It is estimated that 55 percent of all footballs are created in what country",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 37,
                            Answer = "4 years",
                            Content = "The world cup takes place every?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 38,
                            Answer = "gold",
                            Content = "The world cup trophy is made of?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 39,
                            Answer = "mexico",
                            Content = "The only country to host the world cup twice?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 40,
                            Answer = "real madrid",
                            Content = "What team has won the most champions league?",
                            QuizId = 2
                        });
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.QuestionOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            QuestionOptionId = 1,
                            Content = "62",
                            QuestionId = 1
                        },
                        new
                        {
                            QuestionOptionId = 2,
                            Content = "64",
                            QuestionId = 1
                        },
                        new
                        {
                            QuestionOptionId = 3,
                            Content = "54",
                            QuestionId = 1
                        },
                        new
                        {
                            QuestionOptionId = 4,
                            Content = "52",
                            QuestionId = 1
                        },
                        new
                        {
                            QuestionOptionId = 5,
                            Content = "rapid",
                            QuestionId = 2
                        },
                        new
                        {
                            QuestionOptionId = 6,
                            Content = "classical",
                            QuestionId = 2
                        },
                        new
                        {
                            QuestionOptionId = 7,
                            Content = "blitz",
                            QuestionId = 2
                        },
                        new
                        {
                            QuestionOptionId = 8,
                            Content = "modern",
                            QuestionId = 2
                        },
                        new
                        {
                            QuestionOptionId = 9,
                            Content = "international master",
                            QuestionId = 3
                        },
                        new
                        {
                            QuestionOptionId = 10,
                            Content = "chess master",
                            QuestionId = 3
                        },
                        new
                        {
                            QuestionOptionId = 11,
                            Content = "grand master",
                            QuestionId = 3
                        },
                        new
                        {
                            QuestionOptionId = 12,
                            Content = "chess expert",
                            QuestionId = 3
                        },
                        new
                        {
                            QuestionOptionId = 13,
                            Content = "knights",
                            QuestionId = 4
                        },
                        new
                        {
                            QuestionOptionId = 14,
                            Content = "crowns",
                            QuestionId = 4
                        },
                        new
                        {
                            QuestionOptionId = 15,
                            Content = "castles",
                            QuestionId = 4
                        },
                        new
                        {
                            QuestionOptionId = 16,
                            Content = "bishops",
                            QuestionId = 4
                        },
                        new
                        {
                            QuestionOptionId = 17,
                            Content = "economist theory",
                            QuestionId = 5
                        },
                        new
                        {
                            QuestionOptionId = 18,
                            Content = "classical economics",
                            QuestionId = 5
                        },
                        new
                        {
                            QuestionOptionId = 19,
                            Content = "macro economics",
                            QuestionId = 5
                        },
                        new
                        {
                            QuestionOptionId = 20,
                            Content = "game theory",
                            QuestionId = 5
                        },
                        new
                        {
                            QuestionOptionId = 21,
                            Content = "usa",
                            QuestionId = 6
                        },
                        new
                        {
                            QuestionOptionId = 22,
                            Content = "russia",
                            QuestionId = 6
                        },
                        new
                        {
                            QuestionOptionId = 23,
                            Content = "norway",
                            QuestionId = 6
                        },
                        new
                        {
                            QuestionOptionId = 24,
                            Content = "india",
                            QuestionId = 6
                        },
                        new
                        {
                            QuestionOptionId = 25,
                            Content = "magnus carlsen",
                            QuestionId = 7
                        },
                        new
                        {
                            QuestionOptionId = 26,
                            Content = "wesley so",
                            QuestionId = 7
                        },
                        new
                        {
                            QuestionOptionId = 27,
                            Content = "garry kasparov",
                            QuestionId = 7
                        },
                        new
                        {
                            QuestionOptionId = 28,
                            Content = "fabiano caruana",
                            QuestionId = 7
                        },
                        new
                        {
                            QuestionOptionId = 29,
                            Content = "risks one or more pawns or a minor piece to gain an advantage in position",
                            QuestionId = 8
                        },
                        new
                        {
                            QuestionOptionId = 30,
                            Content = "sacrficing a bishop",
                            QuestionId = 8
                        },
                        new
                        {
                            QuestionOptionId = 31,
                            Content = "none of the above",
                            QuestionId = 8
                        },
                        new
                        {
                            QuestionOptionId = 32,
                            Content = "sacrificing a pawn",
                            QuestionId = 8
                        },
                        new
                        {
                            QuestionOptionId = 33,
                            Content = "deep red",
                            QuestionId = 9
                        },
                        new
                        {
                            QuestionOptionId = 34,
                            Content = "deep fake",
                            QuestionId = 9
                        },
                        new
                        {
                            QuestionOptionId = 35,
                            Content = "deep AI",
                            QuestionId = 9
                        },
                        new
                        {
                            QuestionOptionId = 36,
                            Content = "deep blue",
                            QuestionId = 9
                        },
                        new
                        {
                            QuestionOptionId = 37,
                            Content = "16th",
                            QuestionId = 10
                        },
                        new
                        {
                            QuestionOptionId = 38,
                            Content = "19th",
                            QuestionId = 10
                        },
                        new
                        {
                            QuestionOptionId = 39,
                            Content = "20th",
                            QuestionId = 10
                        },
                        new
                        {
                            QuestionOptionId = 40,
                            Content = "13th",
                            QuestionId = 10
                        },
                        new
                        {
                            QuestionOptionId = 41,
                            Content = "minions",
                            QuestionId = 11
                        },
                        new
                        {
                            QuestionOptionId = 42,
                            Content = "bishop",
                            QuestionId = 11
                        },
                        new
                        {
                            QuestionOptionId = 43,
                            Content = "rooks",
                            QuestionId = 11
                        },
                        new
                        {
                            QuestionOptionId = 44,
                            Content = "pawns",
                            QuestionId = 11
                        },
                        new
                        {
                            QuestionOptionId = 45,
                            Content = "2500",
                            QuestionId = 12
                        },
                        new
                        {
                            QuestionOptionId = 46,
                            Content = "2000",
                            QuestionId = 12
                        },
                        new
                        {
                            QuestionOptionId = 47,
                            Content = "2800",
                            QuestionId = 12
                        },
                        new
                        {
                            QuestionOptionId = 48,
                            Content = "2300",
                            QuestionId = 12
                        },
                        new
                        {
                            QuestionOptionId = 49,
                            Content = "5949 moves",
                            QuestionId = 13
                        },
                        new
                        {
                            QuestionOptionId = 50,
                            Content = "5749 moves",
                            QuestionId = 13
                        },
                        new
                        {
                            QuestionOptionId = 51,
                            Content = "1820 moves",
                            QuestionId = 13
                        },
                        new
                        {
                            QuestionOptionId = 52,
                            Content = "6000 moves",
                            QuestionId = 13
                        },
                        new
                        {
                            QuestionOptionId = 53,
                            Content = "i got your king",
                            QuestionId = 14
                        },
                        new
                        {
                            QuestionOptionId = 54,
                            Content = "it is over",
                            QuestionId = 14
                        },
                        new
                        {
                            QuestionOptionId = 55,
                            Content = "game over",
                            QuestionId = 14
                        },
                        new
                        {
                            QuestionOptionId = 56,
                            Content = "the king is dead",
                            QuestionId = 14
                        },
                        new
                        {
                            QuestionOptionId = 57,
                            Content = "2000",
                            QuestionId = 15
                        },
                        new
                        {
                            QuestionOptionId = 58,
                            Content = "1000",
                            QuestionId = 15
                        },
                        new
                        {
                            QuestionOptionId = 59,
                            Content = "900",
                            QuestionId = 15
                        },
                        new
                        {
                            QuestionOptionId = 60,
                            Content = "1090",
                            QuestionId = 15
                        },
                        new
                        {
                            QuestionOptionId = 61,
                            Content = "rookies",
                            QuestionId = 16
                        },
                        new
                        {
                            QuestionOptionId = 62,
                            Content = "amateurs",
                            QuestionId = 16
                        },
                        new
                        {
                            QuestionOptionId = 63,
                            Content = "noobs",
                            QuestionId = 16
                        },
                        new
                        {
                            QuestionOptionId = 64,
                            Content = "newbies",
                            QuestionId = 16
                        },
                        new
                        {
                            QuestionOptionId = 65,
                            Content = "game of kings",
                            QuestionId = 17
                        },
                        new
                        {
                            QuestionOptionId = 66,
                            Content = "game of the people",
                            QuestionId = 17
                        },
                        new
                        {
                            QuestionOptionId = 67,
                            Content = "game of the youth",
                            QuestionId = 17
                        },
                        new
                        {
                            QuestionOptionId = 68,
                            Content = "game of the holy",
                            QuestionId = 17
                        },
                        new
                        {
                            QuestionOptionId = 69,
                            Content = "S shape",
                            QuestionId = 18
                        },
                        new
                        {
                            QuestionOptionId = 70,
                            Content = "Z shape",
                            QuestionId = 18
                        },
                        new
                        {
                            QuestionOptionId = 71,
                            Content = "none of the above",
                            QuestionId = 18
                        },
                        new
                        {
                            QuestionOptionId = 72,
                            Content = "L shape",
                            QuestionId = 18
                        },
                        new
                        {
                            QuestionOptionId = 73,
                            Content = "the king",
                            QuestionId = 19
                        },
                        new
                        {
                            QuestionOptionId = 74,
                            Content = "the queen",
                            QuestionId = 19
                        },
                        new
                        {
                            QuestionOptionId = 75,
                            Content = "the pawn",
                            QuestionId = 19
                        },
                        new
                        {
                            QuestionOptionId = 76,
                            Content = "the knight",
                            QuestionId = 19
                        },
                        new
                        {
                            QuestionOptionId = 77,
                            Content = "the king",
                            QuestionId = 20
                        },
                        new
                        {
                            QuestionOptionId = 78,
                            Content = "the queen",
                            QuestionId = 20
                        },
                        new
                        {
                            QuestionOptionId = 79,
                            Content = "none of the above",
                            QuestionId = 20
                        },
                        new
                        {
                            QuestionOptionId = 80,
                            Content = "there is no single most important piece",
                            QuestionId = 20
                        },
                        new
                        {
                            QuestionOptionId = 81,
                            Content = "arsenal",
                            QuestionId = 21
                        },
                        new
                        {
                            QuestionOptionId = 82,
                            Content = "liverpool",
                            QuestionId = 21
                        },
                        new
                        {
                            QuestionOptionId = 83,
                            Content = "man united",
                            QuestionId = 21
                        },
                        new
                        {
                            QuestionOptionId = 84,
                            Content = "chelsea",
                            QuestionId = 21
                        },
                        new
                        {
                            QuestionOptionId = 85,
                            Content = "spain",
                            QuestionId = 22
                        },
                        new
                        {
                            QuestionOptionId = 86,
                            Content = "norway",
                            QuestionId = 22
                        },
                        new
                        {
                            QuestionOptionId = 87,
                            Content = "france",
                            QuestionId = 22
                        },
                        new
                        {
                            QuestionOptionId = 88,
                            Content = "italy",
                            QuestionId = 22
                        },
                        new
                        {
                            QuestionOptionId = 89,
                            Content = "george best",
                            QuestionId = 23
                        },
                        new
                        {
                            QuestionOptionId = 90,
                            Content = "maradona",
                            QuestionId = 23
                        },
                        new
                        {
                            QuestionOptionId = 91,
                            Content = "messi",
                            QuestionId = 23
                        },
                        new
                        {
                            QuestionOptionId = 92,
                            Content = "c. ronaldo",
                            QuestionId = 23
                        },
                        new
                        {
                            QuestionOptionId = 93,
                            Content = "pogba",
                            QuestionId = 24
                        },
                        new
                        {
                            QuestionOptionId = 94,
                            Content = "neymar",
                            QuestionId = 24
                        },
                        new
                        {
                            QuestionOptionId = 95,
                            Content = "mbappe",
                            QuestionId = 24
                        },
                        new
                        {
                            QuestionOptionId = 96,
                            Content = "messi",
                            QuestionId = 24
                        },
                        new
                        {
                            QuestionOptionId = 97,
                            Content = "number 6",
                            QuestionId = 25
                        },
                        new
                        {
                            QuestionOptionId = 98,
                            Content = "number 11",
                            QuestionId = 25
                        },
                        new
                        {
                            QuestionOptionId = 99,
                            Content = "number 2",
                            QuestionId = 25
                        },
                        new
                        {
                            QuestionOptionId = 100,
                            Content = "number 10",
                            QuestionId = 25
                        },
                        new
                        {
                            QuestionOptionId = 101,
                            Content = "maradona",
                            QuestionId = 26
                        },
                        new
                        {
                            QuestionOptionId = 102,
                            Content = "pele",
                            QuestionId = 26
                        },
                        new
                        {
                            QuestionOptionId = 103,
                            Content = "c. ronaldo",
                            QuestionId = 26
                        },
                        new
                        {
                            QuestionOptionId = 104,
                            Content = "george best",
                            QuestionId = 26
                        },
                        new
                        {
                            QuestionOptionId = 105,
                            Content = "3",
                            QuestionId = 27
                        },
                        new
                        {
                            QuestionOptionId = 106,
                            Content = "2",
                            QuestionId = 27
                        },
                        new
                        {
                            QuestionOptionId = 107,
                            Content = "4",
                            QuestionId = 27
                        },
                        new
                        {
                            QuestionOptionId = 108,
                            Content = "5",
                            QuestionId = 27
                        },
                        new
                        {
                            QuestionOptionId = 109,
                            Content = "4",
                            QuestionId = 28
                        },
                        new
                        {
                            QuestionOptionId = 110,
                            Content = "8",
                            QuestionId = 28
                        },
                        new
                        {
                            QuestionOptionId = 111,
                            Content = "16",
                            QuestionId = 28
                        },
                        new
                        {
                            QuestionOptionId = 112,
                            Content = "32",
                            QuestionId = 28
                        },
                        new
                        {
                            QuestionOptionId = 113,
                            Content = "once",
                            QuestionId = 29
                        },
                        new
                        {
                            QuestionOptionId = 114,
                            Content = "2 times",
                            QuestionId = 29
                        },
                        new
                        {
                            QuestionOptionId = 115,
                            Content = "none of the above",
                            QuestionId = 29
                        },
                        new
                        {
                            QuestionOptionId = 116,
                            Content = "3 times",
                            QuestionId = 29
                        },
                        new
                        {
                            QuestionOptionId = 117,
                            Content = "england",
                            QuestionId = 30
                        },
                        new
                        {
                            QuestionOptionId = 118,
                            Content = "spain",
                            QuestionId = 30
                        },
                        new
                        {
                            QuestionOptionId = 119,
                            Content = "italy",
                            QuestionId = 30
                        },
                        new
                        {
                            QuestionOptionId = 120,
                            Content = "brazil",
                            QuestionId = 30
                        },
                        new
                        {
                            QuestionOptionId = 121,
                            Content = "messi",
                            QuestionId = 31
                        },
                        new
                        {
                            QuestionOptionId = 122,
                            Content = "c. ronaldo",
                            QuestionId = 31
                        },
                        new
                        {
                            QuestionOptionId = 123,
                            Content = "pele",
                            QuestionId = 31
                        },
                        new
                        {
                            QuestionOptionId = 124,
                            Content = "maradona",
                            QuestionId = 31
                        },
                        new
                        {
                            QuestionOptionId = 125,
                            Content = "escobar",
                            QuestionId = 32
                        },
                        new
                        {
                            QuestionOptionId = 126,
                            Content = "adam",
                            QuestionId = 32
                        },
                        new
                        {
                            QuestionOptionId = 127,
                            Content = "shawn",
                            QuestionId = 32
                        },
                        new
                        {
                            QuestionOptionId = 128,
                            Content = "maradona",
                            QuestionId = 32
                        },
                        new
                        {
                            QuestionOptionId = 129,
                            Content = "the enforcer",
                            QuestionId = 33
                        },
                        new
                        {
                            QuestionOptionId = 130,
                            Content = "the decision maker",
                            QuestionId = 33
                        },
                        new
                        {
                            QuestionOptionId = 131,
                            Content = "the master",
                            QuestionId = 33
                        },
                        new
                        {
                            QuestionOptionId = 132,
                            Content = "the referee",
                            QuestionId = 33
                        },
                        new
                        {
                            QuestionOptionId = 133,
                            Content = "10",
                            QuestionId = 34
                        },
                        new
                        {
                            QuestionOptionId = 134,
                            Content = "5",
                            QuestionId = 34
                        },
                        new
                        {
                            QuestionOptionId = 135,
                            Content = "11",
                            QuestionId = 34
                        },
                        new
                        {
                            QuestionOptionId = 136,
                            Content = "12",
                            QuestionId = 34
                        },
                        new
                        {
                            QuestionOptionId = 137,
                            Content = "pitch",
                            QuestionId = 35
                        },
                        new
                        {
                            QuestionOptionId = 138,
                            Content = "plains",
                            QuestionId = 35
                        },
                        new
                        {
                            QuestionOptionId = 139,
                            Content = "court",
                            QuestionId = 35
                        },
                        new
                        {
                            QuestionOptionId = 140,
                            Content = "none of the above",
                            QuestionId = 35
                        },
                        new
                        {
                            QuestionOptionId = 141,
                            Content = "china",
                            QuestionId = 36
                        },
                        new
                        {
                            QuestionOptionId = 142,
                            Content = "pakistan",
                            QuestionId = 36
                        },
                        new
                        {
                            QuestionOptionId = 143,
                            Content = "india",
                            QuestionId = 36
                        },
                        new
                        {
                            QuestionOptionId = 144,
                            Content = "brazil",
                            QuestionId = 36
                        },
                        new
                        {
                            QuestionOptionId = 145,
                            Content = "3 years",
                            QuestionId = 37
                        },
                        new
                        {
                            QuestionOptionId = 146,
                            Content = "5 years",
                            QuestionId = 37
                        },
                        new
                        {
                            QuestionOptionId = 147,
                            Content = "2 years",
                            QuestionId = 37
                        },
                        new
                        {
                            QuestionOptionId = 148,
                            Content = "4 years",
                            QuestionId = 37
                        },
                        new
                        {
                            QuestionOptionId = 149,
                            Content = "gold",
                            QuestionId = 38
                        },
                        new
                        {
                            QuestionOptionId = 150,
                            Content = "silver",
                            QuestionId = 38
                        },
                        new
                        {
                            QuestionOptionId = 151,
                            Content = "plastic",
                            QuestionId = 38
                        },
                        new
                        {
                            QuestionOptionId = 152,
                            Content = "bronze",
                            QuestionId = 38
                        },
                        new
                        {
                            QuestionOptionId = 153,
                            Content = "france",
                            QuestionId = 39
                        },
                        new
                        {
                            QuestionOptionId = 154,
                            Content = "mexico",
                            QuestionId = 39
                        },
                        new
                        {
                            QuestionOptionId = 155,
                            Content = "brazil",
                            QuestionId = 39
                        },
                        new
                        {
                            QuestionOptionId = 156,
                            Content = "spain",
                            QuestionId = 39
                        },
                        new
                        {
                            QuestionOptionId = 157,
                            Content = "real madrid",
                            QuestionId = 40
                        },
                        new
                        {
                            QuestionOptionId = 158,
                            Content = "barcelona",
                            QuestionId = 40
                        },
                        new
                        {
                            QuestionOptionId = 159,
                            Content = "AC milan",
                            QuestionId = 40
                        },
                        new
                        {
                            QuestionOptionId = 160,
                            Content = "bayern munich",
                            QuestionId = 40
                        });
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            Description = "Fun quiz on chess!",
                            Name = "Chess Quiz"
                        },
                        new
                        {
                            QuizId = 2,
                            Description = "How much do you really know about the most popular sport in the world?",
                            Name = "Soccer Quiz"
                        });
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.UserScore", b =>
                {
                    b.Property<int>("UserScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PlayerScore")
                        .HasColumnType("float");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuizTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserScoreId");

                    b.HasIndex("QuizId");

                    b.ToTable("UserScores");

                    b.HasData(
                        new
                        {
                            UserScoreId = 1,
                            FirstName = "Joshua",
                            LastName = "Giggs",
                            PlayerName = "ChessWiz94",
                            PlayerScore = 90.0,
                            QuizId = 1,
                            QuizTime = new DateTime(2021, 12, 4, 0, 10, 4, 377, DateTimeKind.Local).AddTicks(5320)
                        },
                        new
                        {
                            UserScoreId = 2,
                            FirstName = "John",
                            LastName = "Smith",
                            PlayerName = "John",
                            PlayerScore = 40.0,
                            QuizId = 1,
                            QuizTime = new DateTime(2020, 12, 19, 5, 10, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserScoreId = 3,
                            FirstName = "James",
                            LastName = "Sion",
                            PlayerName = "Qwerty",
                            PlayerScore = 50.0,
                            QuizId = 1,
                            QuizTime = new DateTime(2019, 11, 21, 5, 10, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserScoreId = 4,
                            FirstName = "Phil",
                            LastName = "Scott",
                            PlayerName = "Firmino9",
                            PlayerScore = 100.0,
                            QuizId = 2,
                            QuizTime = new DateTime(2021, 10, 22, 5, 10, 20, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.Question", b =>
                {
                    b.HasOne("ASP.NET_Assignment_04.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.QuestionOption", b =>
                {
                    b.HasOne("ASP.NET_Assignment_04.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ASP.NET_Assignment_04.Models.UserScore", b =>
                {
                    b.HasOne("ASP.NET_Assignment_04.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId");

                    b.Navigation("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
